import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoryblokProvider } from "../src/components/StoryblokProvider";
import { Header } from "../src/components/Header";
import { Footer } from "../src/components/Footer";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import { DM_Sans } from "next/font/google";

storyblokInit({
  accessToken: process.env.STORYBLOK_TOKEN,
  use: [apiPlugin],
});

export {};


const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choose the weights you need
  variable: "--font-dm-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
    <html lang="en">
      <body
        className={`${dmSans.variable} ${geistMono.variable} antialiased pt-40`}
      >
                  <Header />
        {children}
                  <Footer />
      </body>
    </html>
    </StoryblokProvider>
  );
}
